{ pkgs, ... }: {
  home.stateVersion = "24.11"; 

  # --- GHOSTTY CONFIG ---
  home.file.".config/ghostty/config".text = ''
    palette = 0=#494d64
    palette = 1=#ed8796
    palette = 2=#a6da95
    palette = 3=#eed49f
    palette = 4=#8aadf4
    palette = 5=#f5bde6
    palette = 6=#8bd5ca
    palette = 7=#b8c0e0
    palette = 8=#5b6078
    palette = 9=#ed8796
    palette = 10=#a6da95
    palette = 11=#eed49f
    palette = 12=#8aadf4
    palette = 13=#f5bde6
    palette = 14=#8bd5ca
    palette = 15=#a5adcb
    background = #24273a
    foreground = #cad3f5
    cursor-color = #f4dbd6
    selection-background = #44475a
    selection-foreground = #cad3f5

    font-family = "JetBrainsMono Nerd Font"
    font-size = 14
    window-padding-x = 10
    window-padding-y = 10
    macos-option-as-alt = true
  '';

  # --- GIT ---
  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "Miha Oblišar";
        email = "miha.oblishar@gmail.com";
      };
      init.defaultBranch = "main";
    };
  };

  # --- VS CODE ---
  programs.vscode = {
    enable = true;
    profiles.default = {
      extensions = with pkgs.vscode-extensions; [
        bbenoist.nix
        catppuccin.catppuccin-vsc
        catppuccin.catppuccin-vsc-icons
        ms-azuretools.vscode-docker
        ms-kubernetes-tools.vscode-kubernetes-tools
        ms-vscode-remote.vscode-remote-extensionpack
        jnoortheen.nix-ide
      ];
      userSettings = {
        "workbench.colorTheme" = "Catppuccin Macchiato";
        "workbench.iconTheme" = "catppuccin-macchiato";
        "editor.fontSize" = 14;
        "editor.fontFamily" = "'JetBrainsMono Nerd Font', monospace";
        "nix.enableLanguageServer" = true;
        "nix.serverPath" = "nil";
      };
    };
  };

  # --- STARSHIP ---
  programs.starship = {
    enable = true;
    settings = {
      add_newline = false;
      format = "$directory$git_branch$git_status$kubernetes$terraform$character";
      directory = {
        truncation_length = 3;
        fish_style_pwd_dir_length = 1;
      };
      character = {
        success_symbol = "[➜](bold green)";
        error_symbol = "[➜](bold red)";
      };
    };
  };

  # --- FZF ---
  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
    defaultCommand = "fd --type f --strip-cwd-prefix --hidden --follow --exclude .git";
    fileWidgetCommand = "fd --type f --strip-cwd-prefix --hidden --follow --exclude .git";
    colors = {
      "bg+" = "-1";
      "fg+" = "#cad3f5";
      hl = "#ed8796";
      "hl+" = "#ed8796";
      header = "#ed8796";
      info = "#c6a0f6";
      pointer = "#f4dbd6";
      marker = "#f4dbd6";
      prompt = "#c6a0f6";
      spinner = "#f4dbd6";
    };
  };

  # --- ZOXIDE (The 'cd' killer) ---
  programs.zoxide = {
    enable = true;
    enableZshIntegration = true;
  };

  # --- ZSH ---
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    # Plugins for a better experience
    plugins = [
      {
        name = "fzf-tab";
        src = pkgs.zsh-fzf-tab;
        file = "share/fzf-tab/fzf-tab.plugin.zsh";
      }
    ];

    initContent = ''
      # Initialize Starship
      eval "$(starship init zsh)"

      # 2. 1Password CLI Plugin Integration
      # This looks for the aliases generated by 'op plugin init'
      export OP_BIOMETRIC_UNLOCK_ENABLED=true
      if [ -f ~/.config/op/plugins.sh ]; then
        source ~/.config/op/plugins.sh
      fi
      
      # fzf-tab tweaks: preview directory content when completing cd
      zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
    '';

    shellAliases = {
      ls = "eza --icons --git --group-directories-first";
      ll = "eza -lh --icons --git --group-directories-first";
      la = "eza -a --icons --git --group-directories-first";
      cat = "bat";
      grep = "rg";
      k = "kubectl";
      nix-switch = "sudo darwin-rebuild switch --flake ~/nix-darwin-config#obleey";
      nix-clean = "nix-collect-garbage -d";
      nix-conf = "code ~/nix-darwin-config";
    };
  };

  programs.ssh = {
      enable = true;
      # Silence the warning by being explicit
      enableDefaultConfig = false;

      # This replaces the old extraConfig for a cleaner structure
      matchBlocks = {
        "*" = {
          identityAgent = "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock";
        };
      };
    };
}